### PR TITLE
Replace cookiecutter with Copier

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
Replaces https://github.com/napari/cookiecutter-napari-plugin/pull/190 (at Juan's request, we are moving the PR back to this repo again)

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
I don't know why the Windows python 3.10 CI check just failed - the only information we get is "Subprocess failed", which could mean literally anything failed after a new plugin repo was created and tox run on it. It would be much better if we could make the actual error message that caused it visible.

I'm hoping it's a flaky test. I'll re-run it.

All the CI checks for https://github.com/napari/cookiecutter-napari-plugin/pull/190/checks passed, and this repo should now be in an equivalent state. Also the other Windows CI checks are passing, as are the other python 3.10 checks.

**Comment by jni** [comment]
Thanks @GenevieveBuckley!

On windows it could just be a flaky runner even. 😬 hopefully it just passes. 🤞

**Comment by GenevieveBuckley** [comment]
> On windows it could just be a flaky runner even. 😬 hopefully it just passes. 🤞

Looks like you were right, it's passed now 🎉

**Comment by jni** [comment]
🚀

**Pull request merged**
